<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <InvariantGlobalization>true</InvariantGlobalization>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="CommandLineParser" Version="2.9.1" />
      <PackageReference Include="Csv" Version="2.0.217" />
      <PackageReference Include="Parquet.Net" Version="5.2.0" />
      <PackageReference Include="OpenTAP" Version="$(OpenTapVersion)"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TapResult\TapResult.csproj" />
    </ItemGroup>

</Project>
