# Configure the name of this CI unit. This is the name that appears in the GitHub Actions tab
name: CiCd
# Configure what events trigger this action.
on: [push]

# Configure environment variables that are global to the action defined by this file
env:
  #OPENTAP_COLOR: auto # github messes with the "auto" color detection (i.e. it has no effect), and the "always" option breaks a lot of things
  OPENTAP_ANSI_COLORS: true
  OPENTAP_NO_UPDATE_CHECK: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_CONSOLE_ANSI_COLOR: true

jobs:

  ##############
  ### BUILD   ##
  ##############

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: 'true'
      - uses: actions/setup-dotnet@v5
        with:
         dotnet-version: '9.0.x'
         cache: 'false'
      - name: Restore Dependencies
        run: dotnet restore Master.sln
      - name: Fix Spark nuget package
        run: ./LinuxFixSparkNuget.sh
      - name: ls
        run: ls ~/.nuget/packages/microsoft.spark/2.3.0
      - name: Restore again with no-cache
        run: dotnet restore Master.sln --no-cache --force
      # Build your project
      - name: Build
        run: dotnet build -c Release Master.sln --no-restore
      - name: ls
        run: ls ~/.nuget/packages/microsoft.spark/2.3.0
        if: always()
      # Upload the package so it can be downloaded from GitHub, 
      # and consumed by other steps in this workflow
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: tap-package
          retention-days: 7
          path: |
            Master.OpenTAP/bin/Release/netstandard2.0/*.TapPackage

  ##############
  ### TEST    ##
  ##############

  UnitTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: 'true'
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'
      - name: Restore Dependencies
        run: dotnet restore Master.sln
      #- name: Fix Spark nuget package
      #  run: ./LinuxFixSparkNuget.sh
      - name: Test
        run: dotnet test -c Release Master.sln

  ##############
  ### PUBLISH ##
  ##############

  Publish:
    # Only publish on the main branch or if the commit is tagged.
    if: github.ref == 'refs/heads/main' || contains(github.ref, 'refs/heads/release') || contains(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    # This step depends on the build step
    needs:
      - Build
    steps:
      # Download the tap-package artifact from the Build step
      - name: Download TapPackage Arfifact
        uses: actions/download-artifact@v3
        with:
          name: tap-package
          path: .
      # Setup OpenTAP with the PackagePublish package in order to publish the newly created package
      - name: Setup OpenTAP
        uses: opentap/setup-opentap@v1.0
        with:
          version: 9.29.1
          packages: "Repository Client:beta"
      # Publish the package. This requires the package management key to be configured in the 'PUBLIC_REPO_PASS' environment variable.
      - name: Publish Packages
        working-directory: ./
        run: tap repo upload --repository http://packages.opentap.io --token ${{ secrets.PUBLIC_REPO_PASS }} Master*.TapPackage